#!sudo /bin/bash
deluser jasawacharoenkun1 
deluser anbriggs1 
deluser trelliot1 
deluser aekmrey1 
deluser dwfoster1 
deluser mbgalvin 
deluser tho2 
deluser cahreha1 
deluser injohnson2 
deluser jcjoseph2 
deluser kakaiser1 
deluser cmlangston 
deluser bjpiasecki 
deluser dsricker 
deluser daschumerth1 
deluser sesimpson1 
deluser adsluder1 
deluser cwest2 
deluser crwolf1 
deluser tjmitchell1 
deluser jwjohnson7 
############################
#delgroup jasawacharoenkun1 
#delgroup anbriggs1 
#delgroup trelliot1 
#delgroup aekmrey1 
#delgroup dwfoster1 
#delgroup mbgalvin 
#delgroup tho2 
#delgroup cahreha1 
#delgroup injohnson2 
#delgroup jcjoseph2 
#delgroup kakaiser1 
#delgroup cmlangston 
#delgroup bjpiasecki 
#delgroup dsricker 
#delgroup daschumerth1 
#delgroup sesimpson1 
#delgroup adsluder1 
#delgroup cwest2 
#delgroup crwolf1 
#delgroup tjmitchell1 
#delgroup jwjohnson7 